<?php

define("KOMFORTKASSE_ACTIVATE_EXPORT_DEFAULT", true);
define("KOMFORTKASSE_ACTIVATE_UPDATE_DEFAULT", true);
define("KOMFORTKASSE_PAYMENT_METHODS_DEFAULT", 'moneyorder,eustandardtransfer');
define("KOMFORTKASSE_STATUS_OPEN_DEFAULT", '1');
define("KOMFORTKASSE_STATUS_PAID_DEFAULT", '2');
define("KOMFORTKASSE_STATUS_CANCELLED_DEFAULT", '99');
define("KOMFORTKASSE_PAYMENT_CODES_INVOICE_DEFAULT", 'invoice');
define("KOMFORTKASSE_STATUS_OPEN_INVOICE_DEFAULT", '149');
define("KOMFORTKASSE_STATUS_PAID_INVOICE_DEFAULT", '');
define("KOMFORTKASSE_STATUS_CANCELLED_INVOICE_DEFAULT", '');
define("KOMFORTKASSE_PAYMENT_CODES_COD_DEFAULT", 'cod');
define("KOMFORTKASSE_STATUS_OPEN_COD_DEFAULT", '3');
define("KOMFORTKASSE_STATUS_PAID_COD_DEFAULT", '');
define("KOMFORTKASSE_STATUS_CANCELLED_COD_DEFAULT", '');
